#!/bin/sh

ADDONNAME=presencebymac

AUTOSTART_DIR=/etc/config/rc.d
AUTOSTART_SCRIPT=${ADDONNAME}
ADDONDIR=/etc/config/addons/${ADDONNAME}
WWWDIR=/etc/config/addons/www/${ADDONNAME}
CONFIG_URL=/addons/${ADDONNAME}/index.cgi
SCRIPT=${ADDONNAME}.tcl
CMD=${ADDONDIR}/${SCRIPT}
TMPDIR=/tmp

case "$1" in
""|start)
        (crontab -l; echo "*/5 * * * * ${CMD}") | sort - | uniq - | crontab -
        ;;
info)
        echo "Version: 1.0.2"
        echo "Name: ${ADDONNAME}"
        echo "Operations: uninstall"
        echo "Info: Check Presence via MAC"
        echo "Config-Url: ${CONFIG_URL}"
        ;;
restart)
        ;;
stop)
        ;;
uninstall)
        crontab -l | sort - | uniq - | sed "s/$(echo "*/5 * * * * ${CMD}" | sed -e 's/[]\/$*.^|[]/\\&/g')//g" | sed '/^$/d' | crontab -
        rm -f ${AUTOSTART_DIR}/${AUTOSTART_SCRIPT}
        rm -f ${TMPDIR}/presence.state
        rm -rf ${WWWDIR}
        rm -rf ${ADDONDIR}
        ;;
*)
        echo "usage:"
        echo "  ${ADDONNAME} [info|start|stop|restart|uninstall]"
        ;;
esac
