#!/bin/sh

ADDONNAME=presencebymac

RCDDIR=/usr/local/etc/config/rc.d
ADDONDIR=/usr/local/etc/config/addons/${ADDONNAME}
WWWDIR=/usr/local/etc/config/addons/www/${ADDONNAME}
TMPDIR=/tmp
DROPBEARKEY=/usr/local/addons/dropbear/dropbearkey

if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "installing ${ADDONNAME}      "
  mount -t yaffs /dev/mtdblock3 /usr/local
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  mount -t ubifs ubi1:user /usr/local
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  mount /usr/local
fi

# Autostart-Script anlegen
cp rc.d/${ADDONNAME} ${RCDDIR}
chmod +x ${RCDDIR}/${ADDONNAME}

# Web-Konfiguration anlegen
mkdir -p ${WWWDIR}
cp -rp www/* ${WWWDIR}
chmod -R 755 ${WWWDIR}

# Addon-Verzeichnis anlegen
mkdir -p ${ADDONDIR}
cp -rp addon/* ${ADDONDIR}
chmod -R 755 ${ADDONDIR}
chown -R root ${ADDONDIR}
chgrp -R root ${ADDONDIR}

# SSH KEYGEN
mkdir -p ${ADDONDIR}/modules/ssh
if [ "$1" = "" && -f ${DROPBEARKEY} ]; then
  ${DROPBEARKEY} -t rsa -f ${ADDONDIR}/modules/ssh/id_rsa
  ${DROPBEARKEY} -y -f ${ADDONDIR}/modules/ssh/id_rsa | grep "^ssh-rsa " >> ${ADDONDIR}/modules/ssh/id_rsa.pub
elif  [ "$1" = "CCU2" ]; then
  ssh-keygen -t rsa -N "" -f ${ADDONDIR}/modules/ssh/id_rsa
fi

# Alte conf kopieren
if [ -f ${TMPDIR}/${ADDONNAME}.conf ]; then
  cp ${TMPDIR}/${ADDONNAME}.conf ${ADDONDIR}/${ADDONNAME}.conf
fi

# sync filesystem to make sure all changes are written to disk
sync

if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "Reboot...             "
  lcdtool -a 0x40 -t bin 00
  echo "x" > /dev/watchdog
  reboot
  while true ; do true ;  done
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  # CCU2 always reboots after Addon/Firmware Update
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  # RASPBERRYMATIC always reboots after Addon/Firmware Update
fi
