#!/bin/sh

ADDONENAME=presencebymac

RCDDIR=/usr/local/etc/config/rc.d
ADDONDIR=/usr/local/etc/config/addons/$ADDONENAME
WWWDIR=/usr/local/etc/config/addons/www/$ADDONENAME

if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "installing $ADDONNAME      "
  mount -t yaffs /dev/mtdblock3 /usr/local
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  mount -t ubifs ubi1:user /usr/local
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  mount /usr/local
fi

# Autostart-Script anlegen
cp ./rc.d/$ADDONENAME $RCDDIR
chmod +x $RCDDIR/$ADDONENAME

# Web-Konfiguration anlegen
mkdir -p $WWWDIR
cp -rp www/* $WWWDIR
chmod -R 755 $WWWDIR

# Addon-Verzeichnis anlegen
mkdir -p $ADDONDIR
cp -rp addon/* $ADDONDIR
chmod -R 755 $ADDONDIR
chown -R root $ADDONDIR
chgrp -R root $ADDONDIR

# SSH KEYGEN
mkdir -p $ADDONDIR/modules/sophos
ssh-keygen -t rsa -N "" -f $ADDONDIR/modules/sophos/id_rsa

# Crontab anlegen
(crontab -l; echo "*/5 * * * * ${ADDONDIR}/presence.tcl")  | sort - | uniq - | crontab -

# sync filesystem to make sure all changes are written to disk
sync

if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "Reboot...             "
  lcdtool -a 0x40 -t bin 00
  echo "x" > /dev/watchdog
  reboot
  while true ; do true ;  done
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  # CCU2 always reboots after Addon/Firmware Update
elif [ "$1" = "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  # RASPBERRYMATIC always reboots after Addon/Firmware Update
fi
