#!/bin/sh

ADDONENAME=presence

RCDDIR=/usr/local/etc/config/rc.d
ADDONDIR=/usr/local/etc/config/addons/$ADDONENAME
WWWDIR=/usr/local/etc/config/addons/www/$ADDONENAME
CONFIGDIR=/usr/local/etc/config


mkdir -p /mnt
if [ "$1" == "CCU2" ]; then
	echo "CCU2"
	mount -t ubifs ubi0:root /mnt
	mount -t ubifs ubi1:user /usr/local
else
	echo "CCU1"
	mount -t yaffs /dev/mtdblock3 /mnt
fi

# Autostart-Script anlegen
cp ./rc.d/$ADDONENAME $RCDDIR
chmod +x $RCDDIR/$ADDONENAME

# Web-Konfiguration anlegen
mkdir -p $WWWDIR
cp -rp www/* $WWWDIR
chmod -R 755 $WWWDIR

# Addon-Verzeichnis anlegen
mkdir -p $ADDONDIR
cp -rp addon/* $ADDONDIR
chmod -R 755 $ADDONDIR
chown -R root $ADDONDIR
chgrp -R root $ADDONDIR

# Crontab anlegen
(crontab -l; echo "*/5 * * * * ${ADDONDIR}/presence.tcl")  | sort - | uniq - | crontab -

if [ "$1" == "CCU2" ]; then
	echo "dismount"
	umount /usr/local
	umount /mnt
else
	echo "dismount"
	umount /mnt
	
	echo Rebooting...
	lcdtool "Reboot...             "
	lcdtool -a 0x40 -t bin 00

	echo "x" > /dev/watchdog
	reboot
	while true ; do true ;  done
fi
