#!/bin/sh

ADDONNAME=presencebymac

AUTOSTART_DIR=/etc/config/rc.d
AUTOSTART_SCRIPT=$ADDONNAME
ADDONDIR=/etc/config/addons/$ADDONNAME
WWWDIR=/usr/local/etc/config/addons/www/$ADDONNAME
CONFIG_URL=/addons/$ADDONNAME/index.cgi
SCRIPT=$ADDONNAME.tcl

case "$1" in
""|start)
        ;;
info)
        echo "Version: 1.0"
        echo "Name: $ADDONNAME"
        echo "Operations: uninstall"
        echo "Info: Check Presence via MAC"
        echo "Config-Url: $CONFIG_URL"
        ;;
restart)
        ;;
stop)
        ;;
uninstall)
        CMD=${ADDONDIR}/${SCRIPT}
        (crontab -l; echo "*/5 * * * * ${CMD}") | sort - | uniq - | sed "s/$(echo "*/5 * * * * ${CMD}" | sed -e 's/[]\/$*.^|[]/\\&/g')//g" | sed '/^$/d' | crontab -
        rm -f $AUTOSTART_DIR/$AUTOSTART_SCRIPT
        rm -f /tmp/presence.state
        rm -rf $WWWDIR
        rm -rf $ADDONDIR
        ;;
*)
        echo "usage:"
        echo "  $ADDONNAME [info|start|stop|restart|uninstall]"
        ;;
esac
